name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  envied: ^0.5.2
  path: ^1.8.0
  replicate:
    path: ../

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  lints: ^2.0.0
  test: ^1.16.0
