name: replicate
version: 0.9.5
description: A community-maintained Dart client package for Replicate.com, this package let you interact with Replicate.com APIs and create predictions from the available machine learning models.
repository: https://github.com/anasfik/replicate

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  http: ^0.13.5
  meta: ^1.9.0
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
